name: 'openpilot env setup, with retry on failure'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      submodules: true
  - uses: ./.github/workflows/setup-with-retry
    with:
      docker_hub_pat: ${{ secrets.DOCKER_HUB_PAT }}
  - name: Build openpilot
    timeout-minutes: ${{ ((steps.restore-scons-cache.outputs.cache-hit == 'true') && 10 || 30) }} # allow more time when we missed the scons cache
    run: ${{ env.RUN }} "scons -j$(nproc)"
  - name: Run unit tests
    timeout-minutes: 15
    run: |
      ${{ env.RUN }} "source selfdrive/test/setup_xvfb.sh && \
                      $PYTEST --timeout 60 -m 'not slow' && \
                      ./selfdrive/ui/tests/create_test_translations.sh && \
                      QT_QPA_PLATFORM=offscreen ./selfdrive/ui/tests/test_translations && \
                      pytest ./selfdrive/ui/tests/test_translations.py"
  - name: "Upload coverage to Codecov"
    uses: codecov/codecov-action@v4
    with:
      name: ${{ github.job }}
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}