name: ci_quality_report

on:
  push:
    branches:
      - master
  # TODO: cron weekly
  workflow_dispatch:
    inputs:
      n:
        description: 'Number of times to run CI jobs'
        default: 4
        required: true
        type: number

env:
  N: ${{ github.event.inputs.n || '4' }}

jobs:
  generate-matrix-strategy:
    name: generate matrix strategy
    runs-on: ubuntu-latest
    outputs:
      generated_matrix: ${{ steps.gen.outputs.generated_matrix }}
    steps:
      - id: gen
        run: |
          total_runs=${{ env.N }}
          matrix_count=4
          runs_per_matrix=$((total_runs / matrix_count))
          generated_matrix=$(python3 -c "import json; print(json.dumps({ 'run_number' : [x for x in range($runs_per_matrix)] }))")
          echo $generated_matrix
          echo "generated_matrix=$generated_matrix" >> $GITHUB_OUTPUT

  selfdrive_tests_0:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/selfdrive_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_selfdrive_tests_0

  selfdrive_tests_1:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/selfdrive_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_selfdrive_tests_1

  selfdrive_tests_2:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/selfdrive_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_selfdrive_tests_2

  selfdrive_tests_3:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/selfdrive_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_selfdrive_tests_3

  tools_tests_0:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/tools_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_tools_tests_0

  tools_tests_1:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/tools_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_tools_tests_1

  tools_tests_2:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/tools_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_tools_tests_2

  tools_tests_3:
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    uses: signed-long/openpilot/.github/workflows/tools_tests.yaml@master
    with:
      run_number: ${{ matrix.run_number }}_tools_tests_3
