name: ci_quality_report

on:
  push:
    branches:
      - master
  # TODO: cron weekly
  workflow_dispatch:
    inputs:
      n:
        description: 'Number of times to run CI jobs'
        default: 4
        required: true
        type: number

env:
  N: ${{ github.event.inputs.n || '4' }}

jobs:
  generate-matrix-strategy:
    name: generate matrix strategy
    runs-on: ubuntu-latest
    outputs:
      generated_matrix: ${{ steps.gen.outputs.generated_matrix }}
    steps:
      - id: gen
        run: |
          generated_matrix=$(python3 -c "import json; print(json.dumps({ 'run_number' : [x for x in range(${{ env.N }})] }))")
          echo $generated_matrix
          echo "generated_matrix=$generated_matrix" >> $GITHUB_OUTPUT

  unit-tests:
    name: run selfdrive tests
    needs: generate-matrix-strategy
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/unit-tests

  # tools_tests:
  #   name: run tools tests
  #   needs: generate-matrix-strategy
  #   strategy:
  #     matrix: ${{ fromJson(needs.generate-matrix-strategy.outputs.generated_matrix) }}
    # uses: signed-long/openpilot/.github/workflows/tools_tests.yaml@master