name: stargz image optimize
on:
  workflow_dispatch:


jobs:
  optimize-image:
    runs-on: ubuntu-latest
    steps:
      - name: Optimize image
        run: |
          git clone https://github.com/containerd/stargz-snapshotter.git
          cd stargz-snapshotter/cmd/
          sudo go run ctr-remote/main.go image pull ghcr.io/commaai/openpilot-base:latest
          sudo go run ctr-remote/main.go image optimize --oci \
           --entrypoint='[ "/bin/bash", "-c" ]' --args='[ "source selfdrive/test/setup_xvfb.sh && export MAPBOX_TOKEN='pk.eyJ1Ijoiam5ld2IiLCJhIjoiY2xxNW8zZXprMGw1ZzJwbzZneHd2NHljbSJ9.gV7VPRfbXFetD-1OVF0XZg' && pytest --continue-on-collection-errors --cov --cov-report=xml --cov-append --durations=0 --durations-min=5 --hypothesis-seed 0 -n logical --timeout 60 -m 'not slow' && ./selfdrive/ui/tests/create_test_translations.sh && QT_QPA_PLATFORM=offscreen ./selfdrive/ui/tests/test_translations && ./selfdrive/ui/tests/test_translations.py" ]' \
           ghcr.io/commaai/openpilot-base:latest \
           ghcr.io/signed-long/openpilot-base:scons-optimized
